# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CzDZnFq4QJqJNt7Oyxw5qMmY683PDNAV
"""

# streamlit_app/app.py

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

st.set_page_config(page_title="Grupo Juyo", layout="wide")

# Carátula
st.image("https://copilot.microsoft.com/th/id/BCO.3345d9e9-667d-460a-91a0-b556a8c6e75d.png", use_column_width=True)
st.title("Modelamiento Grupo Juyo")

# Menú lateral
menu = st.sidebar.radio("Menú principal", ["Mapa", "EDA", "Modelos"])

# Sección: Mapa
if menu == "Mapa":
    st.subheader("Distribución geográfica de gaseosas")
    st.write("Aquí se mostrará el mapa interactivo si se cuenta con coordenadas.")
    # Ejemplo básico (puedes reemplazar con folium o plotly si tienes lat/lon)
    st.map(pd.DataFrame({
        'lat': [-10.67, -10.68, -10.69],
        'lon': [-76.25, -76.26, -76.27]
    }))

# Sección: EDA
elif menu == "EDA":
    tipo_eda = st.radio("Tipo de EDA", ["Crudo", "Procesado"])

    if tipo_eda == "Crudo":
        st.subheader("EDA - Datos crudos")
        df = pd.read_csv("data/raw/data6_corregido.csv")
    else:
        st.subheader("EDA - Datos procesados")
        df = pd.read_csv("data/features/data6_features.csv")

    st.write("Vista general:")
    st.dataframe(df.head())

    st.write("Estadísticas descriptivas:")
    st.write(df.describe())

    st.write("Valores nulos:")
    st.write(df.isnull().sum())

    st.write("Correlaciones:")
    plt.figure(figsize=(10, 6))
    sns.heatmap(df.corr(), annot=True, cmap="viridis")
    st.pyplot(plt)

    st.write("Distribuciones:")
    df.select_dtypes(include="number").hist(figsize=(12, 8))
    st.pyplot(plt)

# Sección: Modelos
elif menu == "Modelos":
    st.subheader("Predicción con modelos del Grupo Juyo")

    modelos_disponibles = {
        "Cantidad comprada": "modelo_cantidad.pkl",
        "Probabilidad de compra": "modelo_compra.pkl",
        "Día de compra": "modelo_dia_compra.pkl",
        "Producto comprado": "modelo_producto.pkl"
    }

    seleccion = st.selectbox("Selecciona un modelo", list(modelos_disponibles.keys()))
    modelo_path = f"models/{modelos_disponibles[seleccion]}"

    try:
        with open(modelo_path, "rb") as f:
            modelo = pickle.load(f)

        df = pd.read_csv("data/features/data6_features.csv")

        st.write("Datos de entrada:")
        st.dataframe(df.head())

        pred = modelo.predict(df)

        st.write(f"Predicciones para: {seleccion}")
        st.write(pred)

        if seleccion == "Cantidad comprada":
            st.bar_chart(pred)
        elif seleccion == "Día de compra":
            st.bar_chart(pd.Series(pred).value_counts().sort_index())
        elif seleccion == "Producto comprado":
            st.write("Distribución de productos:")
            st.bar_chart(pd.Series(pred).value_counts())
        elif seleccion == "Probabilidad de compra":
            st.line_chart(pred)

    except Exception as e:
        st.error(f"No se pudo cargar el modelo: {e}")